### ISSUE TITLE
[ARM, Android 13] LiteGapps fails to initialize or install on aarch64

### ISSUE THREAD

**Issue by starfoxdot64** [litegapps/litegapps#2]
Currently attempting to install the Core package for Android 13, but the arm installers don't seem to work with any of my aarch64 devices (64-bit CPU, 32-bit kernel).

I've tried a few things to resolve the issues I'm facing. The first is from the Kopi Installer failing to make the /dev/kopi directory:
`- failed make dir /tmp/kopi`
`Updater process ended with ERROR: 1`

The installer produces no logs after install, but manages to break TWRP's terminal and access to all commands afterwards until reboot:
`Child process exited.`
`Child process exited.`

I can get my hands dirty to get the Kopi Installer to work by editing the install script to use /tmp/kopi and making the directory myself, but the architecture checks are in every addon and fail to recognize the kernel's architecture properly as arm.

```
Device 1: Samsung Galaxy Tab A 10.1 (2019)
CPU: Exynos 7904
ROM: TrebleDroid 13 GSI (arm32_binder64 variant)

Device 2: Samsung Galaxy A11
CPU: Qualcomm Snapdragon 450
ROM: Lineage 20 GSI (based on TrebleDroid, arm32_binder64 variant)
```

**Comment by wahyu6070** [comment]
Send build.prop,,(failed to recognize your device architecture)

**Comment by starfoxdot64** [comment]
Here's these. I included both the build.prop from my GSI image (it's RW, I made sure of that) and from my OEM's vendor partition.


[gsi-build.prop.md](https://github.com/litegapps/litegapps/files/11679396/gsi-build.prop.md)
[oem-build.prop.md](https://github.com/litegapps/litegapps/files/11679397/oem-build.prop.md)

**Comment by wahyu6070** [comment]
it looks like the installer can't read and write the partition,maybe because of wrong mounting,,can you provide log or at least screenshot

**Comment by starfoxdot64** [comment]
I can't provide a log right this moment, but I will later. It's been a few months since this issue was started, but I'm sure I'll have the same outcome regardless of time.

If I remember right, I also tried this with a Samsung Galaxy Tab A 10.1 (2019 model), which had similar issues unless I installed the arm package as a Magisk module on either device.

**Comment by wahyu6070** [comment]
I think this is a problem with the wrong mount, so it can't read and write partitions

**Comment by wahyu6070** [comment]
what version did you install?
