### ISSUE TITLE
Please support for Kernel SU

### ISSUE THREAD

**Issue by FahimAnayet** [litegapps/litegapps#3]
Although litegapps could be install via ksu. But after completing installation there is no play store or calendar sync etc. Maybe I am missing something?
 I've used:

> LiteGapps: v2.8 lite
> API: 33
> My Android version 13

**Comment by wahyu6070** [comment]
we don't support kernel su yet

**Comment by wahyu6070** [comment]
Kernelsu installation is support v3.2+
