### ISSUE TITLE
[Question] How should i handle Major Android Updates?

### ISSUE THREAD

**Issue by 0xIO32** [litegapps/litegapps#4]
What should i do when i upgrade for example from Android 13 to Android 14?

Should i remove the module before the upgrade and install the version with Android 14 after the upgrade?
Or should i upgrade and before booting into the upgraded os update the module via the recovery?

(Installation systemless via Magisk on LineageOS)

Just that i know in advance

**Comment by wahyu6070** [comment]
To upgrade the OS, we highly recommend doing a clean flash and reinstalling LiteGapps
