### ISSUE TITLE
Phishing intrusive popups

### ISSUE THREAD

**Issue by Draygon0** [litegapps/litegapps#6]
This is completely unacceptable especially on a Github hosted website. There are much more effective ways of displaying ads and not talking about the scammy type as seen in the image attached. Hope you consider making adequate changes or I will have no choice but to report this repository again. Thank you for your time.
![image](https://github.com/user-attachments/assets/aef0e353-4925-4f60-b131-a33899e03949)

**Comment by wahyu6070** [comment]
I have considered your input, we need funding for this project to stay alive and growing. If you do not agree with our advertising you can use another project that suits you

**Comment by wahyu6070** [comment]
but we will try to fix it to make the ads more friendly
